apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: victoria-metrics
spec:
  interval: 5m
  url: https://victoriametrics.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  releaseName: vm-k8s
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
  interval: 5m
  # Default values
  # https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/README.md
  values:
    grafana:
      admin:
        existingSecret: vm-k8s-grafana
      grafana.ini:
        auth.basic:
          enabled: false
        auth.proxy:
          enabled: true
          header_name: X-Auth-Request-User
          header_property: username
          auto_sign_up: true
          sync_ttl: 60
          headers: Email:X-Auth-Request-Email
        auth:
          disable_login_form: true
        server:
          domain: stehessel.org
          root_url: https://grafana.stehessel.org
          serve_from_sub_path: true
        users:
          auto_assign_org_role: Editor
      resources:
        limits:
          memory: 2048Mi
        requests:
          cpu: 100m
          memory: 512Mi
    kubelet:
      spec:
        interval: "60s"
