apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-system
resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml
  # - route.yaml
  - secret.yaml
  - service.yaml
