apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  releaseName: vm-k8s
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
  interval: 5m
  # Default values
  # https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/README.md
  values:
    grafana:
      admin:
        existingSecret: vm-k8s-grafana
      grafana.ini:
        auth:
          basic:
            enabled: false
          proxy:
            enabled: true
            header_name: X-Auth-Request-User
            header_property: username
            auto_sign_up: true
            sync_ttl: 60
            headers: Email:X-Auth-Request-Email
        server:
          domain: stehessel.org
          root_url: https://grafana.stehessel.org
          serve_from_sub_path: true
        users:
          allow_sign_up: false
          auto_assign_org: true
          auto_assign_org_role: Viewer
      resources:
        limits:
          memory: 1024Mi
        requests:
          cpu: "100m"
          memory: 1024Mi
