apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  releaseName: vm-k8s
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
  interval: 5m
  # Default values
  # https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/README.md
  values:
    grafana:
      # admin:
      #   existingSecret: vm-k8s-grafana
      grafana.ini:
        auth:
          basic:
            enabled: false
          disable_login_form: true
          proxy:
            enabled: true
            header_name: X-Auth-Request-User
            header_property: username
            auto_sign_up: true
            sync_ttl: 60
            headers: Email:X-Auth-Request-Email

      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: "0.5"
          memory: 512Mi
