apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
spec:
  parentRefs:
    - name: gateway
      namespace: ingress
      sectionName: http
  hostnames:
    - grafana.stehessel.org
  rules:
    - backendRefs:
        - name: vm-k8s-grafana
          namespace: victoria-metrics
          port: 80
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
            port: 443
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: podinfo
spec:
  parentRefs:
    - name: gateway
      namespace: ingress
      sectionName: https
  hostnames:
    - grafana.stehessel.org
  rules:
    - backendRefs:
        - name: vm-k8s-grafana
          namespace: victoria-metrics
          port: 80
# ---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: http-filter-redirect
# spec:
#   parentRefs:
#     - name: gateway
#       namespace: ingress
#       sectionName: http
#   hostnames:
#     - metrics.stehessel.org
#   rules:
#     - backendRefs:
#         - name: vmsingle-vm-k8s-victoria-metrics-k8s-stack
#           namespace: victoria-metrics
#           port: 8429
#       filters:
#         - type: RequestRedirect
#           requestRedirect:
#             scheme: https
#             statusCode: 301
#             port: 443
# ---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: podinfo
# spec:
#   parentRefs:
#     - name: gateway
#       namespace: ingress
#       sectionName: https
#   hostnames:
#     - metrics.stehessel.org
#   rules:
#     - backendRefs:
#         - name: vmsingle-vm-k8s-victoria-metrics-k8s-stack
#           namespace: victoria-metrics
#           port: 8429
# ---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: http-filter-redirect
# spec:
#   parentRefs:
#     - name: gateway
#       namespace: ingress
#       sectionName: http
#   hostnames:
#     - alerts.stehessel.org
#   rules:
#     - backendRefs:
#         - name: vmalert-vm-k8s-victoria-metrics-k8s-stack
#           namespace: victoria-metrics
#           port: 8080
#       filters:
#         - type: RequestRedirect
#           requestRedirect:
#             scheme: https
#             statusCode: 301
#             port: 443
# ---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: podinfo
# spec:
#   parentRefs:
#     - name: gateway
#       namespace: ingress
#       sectionName: https
#   hostnames:
#     - alerts.stehessel.org
#   rules:
#     - backendRefs:
#         - name: vmalert-vm-k8s-victoria-metrics-k8s-stack
#           namespace: victoria-metrics
#           port: 8080
