apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: velero
spec:
  interval: 5m
  url: https://vmware-tanzu.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  labels:
    app.kubernetes.io/name: velero
spec:
  releaseName: velero
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: velero
  interval: 5m
  # Default values
  # https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
  values:
    credentials:
      name: velero
    configuration:
      backupStorageLocation:
        - bucket: stehessel-homelab-velero
          config:
            region: us-east-1 # Dummy region required by the AWS plugin.
            s3ForcePathStyle: true
            s3Url: https://s3.us-west-000.backblazeb2.com
          credential:
            name: backblaze
            key: credentials
          default: true
          name: default
          provider: velero.io/aws
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    deployNodeAgent: true
    nodeAgent:
      privileged: true
    resources:
      limits:
        cpu: null
    schedules:
      homelab:
        disabled: false
        schedule: "0 0 * * *"
        template:
          includedNamespaces:
            - mealie
            - syncthing
          storageLocation: default
          ttl: 2160h # 90 days.
        useOwnerReferencesInBackup: false
    snapshotsEnabled: false
    upgradeCRDs: true
