apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  labels:
    app.kubernetes.io/name: velero
spec:
  releaseName: velero
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: velero
  interval: 5m
  # Default values
  # https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
  values:
    configuration:
      backupStorageLocation:
        - bucket: homelab-pvc
          config:
            s3ForcePathStyle: true
          credential:
            name: backblaze
            key: applicationKey
          default: true
          provider: velero.io/aws
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    upgradeCRDs: false
