---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        args:
          - --config-file
          - .github/lint/.yamllint.yaml
  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets
  - repo: local
    hooks:
      - id: validate-kustomize
        name: Validate kustomize resources
        description: Validate Flux custom resources and kustomize overlays using kubeconform.
        entry: ./scripts/validate.sh
        pass_filenames: false
        language: script
        types: [yaml]
