version: "3"

includes:
  terraform:
    dir: ./terraform/hetzner
    taskfile: ./terraform/hetzner

tasks:
  flux:bootstrap:
    cmds:
      - flux bootstrap github
        --owner=stehessel
        --repository=homelab
        --path=flux/clusters/k3s
        --branch=master
        --personal
        --token-auth
    desc: Bootstrap fluxcd operator

  up:
    cmds:
      - task: terraform:init
      - task: terraform:apply
      - task: flux:bootstrap

  destroy:
    deps:
      - terraform:destroy
