version: "3"

includes:
  terraform:
    dir: ./terraform/hetzner
    taskfile: ./terraform/hetzner

tasks:
  hetzner:snapshot:
    cmds:
      - curl -sL https://raw.githubusercontent.com/kube-hetzner/terraform-hcloud-kube-hetzner/master/packer-template/hcloud-microos-snapshots.pkr.hcl -o "hcloud-microos-snapshots.pkr.hcl"
      - cmd: packer build hcloud-microos-snapshots.pkr.hcl
        ignore_error: true
    desc: Build MicroOS snapshots

  flux:bootstrap:
    cmds:
      - flux bootstrap github
        --owner=stehessel
        --repository=homelab
        --path=flux/clusters/k3s
        --branch=master
        --personal
        --token-auth
    desc: Bootstrap fluxcd

  flux:upgrade:
    cmds:
      - flux install --export > ./flux/clusters/k3s/flux-system/gotk-components.yaml
    desc: Upgrade fluxcd

  dns:update:
    cmds:
      - ./scripts/update-dns.nu terraform/hetzner/secrets/base.yaml stehessel.org
    desc: Create DNS record for the load balancer

  up:
    cmds:
      - task: hetzner:snapshot
      - task: terraform:init
      - task: terraform:apply
      - task: flux:bootstrap
      - task: dns:update
    desc: Turn up the cluster and bootstrap fluxcd

  destroy:
    aliases: [down]
    deps:
      - terraform:destroy
    desc: Destroy the cluster
