version: "3"

includes:
  terraform:
    dir: ./terraform/hetzner
    taskfile: ./terraform/hetzner

tasks:
  flux:bootstrap:
    cmds:
      - flux bootstrap github
        --owner=stehessel
        --repository=homelab
        --path=flux/clusters/k3s
        --branch=master
        --personal
        --token-auth
    internal: true
    desc: Bootstrap fluxcd operator

  istio:install:
    cmds:
      - istioctl install --set profile=minimal -y
    internal: true
    desc: Install Istio with minimal capabilities

  up:
    cmds:
      - task: terraform:init
      - task: terraform:apply
      - task: flux:bootstrap
      # - task: istio:install
    desc: Turn up the cluster and bootstrap fluxcd

  destroy:
    deps:
      - terraform:destroy
    desc: Destroy the cluster
