version: "3"

includes:
  terraform:
    dir: ./terraform/hetzner
    taskfile: ./terraform/hetzner

tasks:
  hetzner:snapshot:
    cmds:
      - curl -sL https://raw.githubusercontent.com/kube-hetzner/terraform-hcloud-kube-hetzner/master/packer-template/hcloud-microos-snapshots.pkr.hcl -o "hcloud-microos-snapshots.pkr.hcl"
      - cmd: packer init hcloud-microos-snapshots.pkr.hcl
      - cmd: packer build hcloud-microos-snapshots.pkr.hcl
        ignore_error: true
    desc: Build MicroOS snapshots

  flux:bootstrap:
    cmds:
      - flux bootstrap github
        --owner=stehessel
        --repository=homelab
        --path=flux/clusters/k3s
        --branch=master
        --personal
        --token-auth
    desc: Bootstrap fluxcd

  timoni:bootstrap:
    cmds:
      - timoni bundle apply -f ./timoni/bundles/flux-aio.cue
      - sops --decrypt --extract '["flux"]["sops"]' ./terraform/hetzner/secrets/base.yaml | kubectl apply -f -
      - timoni bundle apply -f ./timoni/bundles/k3s.cue
    desc: Bootstrap fluxcd with timoni

  flux:upgrade:
    cmds:
      - flux install --export > ./flux/clusters/k3s/flux-system/gotk-components.yaml
    desc: Upgrade fluxcd

  istio:manifest:
    cmds:
      - istioctl manifest generate -f ./config/istio/operator.yaml -o ./flux/istio
    desc: Generate Istio manifests based on operator resource

  backup:create:
    cmds:
      - velero backup create --include-namespaces=mealie,syncthing {{.CLI_ARGS}}

  backup:restore:
    cmds:
      - flux suspend kustomization apps
      # - defer: flux resume kustomization apps

      - kubectl delete deployments mealie -n mealie
      - kubectl delete pvc mealie -n mealie
      - kubectl delete deployments syncthing -n syncthing
      - kubectl delete pvc syncthing -n syncthing

      - velero restore create --include-namespaces=mealie,syncthing {{.CLI_ARGS}}

  velero:repo-secret:
    cmds:
      - kubectl delete secret -n velero velero-repo-credentials --ignore-not-found=true
      - sops --decrypt --extract '["velero"]["repo"]' ./terraform/hetzner/secrets/base.yaml | kubectl create -f -
      - kubectl rollout restart deploy velero -n velero

  up:
    cmds:
      - task: hetzner:snapshot
      - task: terraform:init
      - task: terraform:apply
      - task: timoni:bootstrap
    desc: Turn up the cluster and bootstrap fluxcd

  down:
    aliases: [destroy]
    deps:
      - terraform:destroy
    desc: Destroy the cluster
