apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
    - name: https
      hostname: stehessel.org
      protocol: HTTPS
      port: 443
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway-access: "true"
      tls:
        mode: Terminate
        certificateRefs:
          - name: stehessel-org-tls
    - name: syncthing-tcp
      protocol: TCP
      port: 22000
      allowedRoutes:
        kinds:
          - kind: TCPRoute
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway-access: "true"
    - name: syncthing-udp
      protocol: UDP
      port: 22000
      allowedRoutes:
        kinds:
          - kind: UDPRoute
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway-access: "true"
