apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      protocol: HTTP
      port: 8000
      allowedRoutes:
        namespaces:
          from: All
    # - name: websecure
    #   hostname: stehessel.org
    #   protocol: HTTPS
    #   port: 8443
    #   allowedRoutes:
    #     namespaces:
    #       from: Selector
    #       selector:
    #         matchLabels:
    #           gateway-access: "true"
    #   tls:
    #     mode: Terminate
    #     certificateRefs:
    #       - name: stehessel-org-tls
