apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stehessel-org-cert
spec:
  secretName: stehessel-org-tls
  dnsNames:
    - "*.stehessel.org"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-staging
