apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istio-ingress
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: istio-istiod
      namespace: istio-system
  interval: 5m
  # Default values
  # https://istio.io/latest/docs/setup/install/helm
