backblaze:
    keyID: ENC[AES256_GCM,data:w7vtnO6dqUkO299Eqi+Nzy6sgRarvyCmSg==,iv:xxz8hF0aAn143Qg1W3JPLHo3CDVy/xLjYgpWaAVpmT4=,tag:nGTbEysBJ4DuXJo6/kvhrQ==,type:str]
    applicationKey: ENC[AES256_GCM,data:7cqmNg5HhFiachTyFTGPtociTPf3/UhctyfWa7mayw==,iv:7MfbGi57gfKv8QjirN9Qd0tDSrIjOFD3qG1M/Qj2t/E=,tag:ZGEbLGIm8R6668Xxx9DMyw==,type:str]
hcloud:
    token: ENC[AES256_GCM,data:vudrsTh/b3ArlxPrbxNt0yQuhG4boM+17OqsQsbnL2pIQxIx1rSZGEbXtTWelkvqkTt7kWenV4LeQ64Npcf0nA==,iv:29SPRAqScv+EB+ISDiOxAjH8t7DBJb/BhAOx7tB9yV8=,tag:28x8/7cHE20w7zUeNAZfwA==,type:str]
porkbun:
    apiKey: ENC[AES256_GCM,data:Cv2j0CYAfd2KKtRWt0w9L10C3onYL80Rxb5gbX891v32B7zJo75+qOTEhrzO36HwhLjH6IJeJ3rALdLqLAbnWA/bPJM=,iv:nuJiUY8s2/Tyxs2NfS1m2avKGX6P5YtGdW6Gobxl3kU=,tag:6ugKuuuapCN2bhgLE8talA==,type:str]
    secretKey: ENC[AES256_GCM,data:I1OoXRxN5J2v3Ad1FkCBOqqU4m5P5dMMnjw2ilZ0XEZTO8aWOGzuR3OdA13FKDQ1G/ik9P+5NxYQ6S9OJf9H+JAGofU=,iv:ca8Tqtm4OMD/AR4HT2YOqO11iuEDSEylZj7BY+065Ho=,tag:HaRq3V8dGWbscLcL8qIxSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hq2vn8nalmp9plfn4x6x9haxm3dv0jzv2mdx2f8p4ud2xwcdq0sfst6p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWUlJR2FJSk9ScWxIQTdO
            blhHdCs5b3pUS080T3RaaXhYZk1pTlcyUldVClh3ZzF0dTFGYld6NndLdEV3ZjBq
            V21vYmtmdzJPTkFyWlVrZkdOZzhNeFEKLS0tIG96Y21HaStEdjN3SHI0TllVT1N5
            MlhCdTR2bDNwbkFZRURzb2JRZ0tjMDQK0dwZKjoGgqdz30+ACagLD1xRX6Nx1Rm+
            qud65AxzGYPQ8qxjaH5uY66zj+kPLOEmfoTUbsOctMX5mEcumnh4bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-10T04:16:40Z"
    mac: ENC[AES256_GCM,data:7qympIJi/FB+rYNicHj9691w54+1Ad4e/lwN0jBrCIrnrLw4/rt8VIDIuOSE7F51ga2JKzxYwWHzBqghx3HrN3bdCl/O5xIrNGX6LvVMvwLoBEOOiyvW+z12RNx7W0wavExwgS8o/wdPFOVg9i3ozs+o/VmKOmOwyhaekA1m4iE=,iv:Z32X0K3e77LLagYh2L+6KoCZB+pNt7FFfa8iuQruiJw=,tag:ZdIMYmh70BVn2gJPdwBV8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
