backblaze:
    keyID: ENC[AES256_GCM,data:w7vtnO6dqUkO299Eqi+Nzy6sgRarvyCmSg==,iv:xxz8hF0aAn143Qg1W3JPLHo3CDVy/xLjYgpWaAVpmT4=,tag:nGTbEysBJ4DuXJo6/kvhrQ==,type:str]
    applicationKey: ENC[AES256_GCM,data:7cqmNg5HhFiachTyFTGPtociTPf3/UhctyfWa7mayw==,iv:7MfbGi57gfKv8QjirN9Qd0tDSrIjOFD3qG1M/Qj2t/E=,tag:ZGEbLGIm8R6668Xxx9DMyw==,type:str]
hcloud:
    token: ENC[AES256_GCM,data:vudrsTh/b3ArlxPrbxNt0yQuhG4boM+17OqsQsbnL2pIQxIx1rSZGEbXtTWelkvqkTt7kWenV4LeQ64Npcf0nA==,iv:29SPRAqScv+EB+ISDiOxAjH8t7DBJb/BhAOx7tB9yV8=,tag:28x8/7cHE20w7zUeNAZfwA==,type:str]
porkbun:
    apiKey: ENC[AES256_GCM,data:fANsS01mE24dW9wp46/zi2zPMRCqcgyWSBNtAbOiLnEQdplLbZd6c2SoFBaVqrZuxmZ21z7cTDoAXMTbx6Dto8emlSs=,iv:3OWRt5aQt9gaPKXeEQElytuZzIJKgTmMpQ0/336n3SU=,tag:IZg5Vr7Bwa2+nPavo6f97Q==,type:str]
    secretKey: ENC[AES256_GCM,data:3G7aZexCT5LwAtFyUxc+YChQ8Nb7QKtbKz8wqgd1LTL7VRfgV3P2POUrJl2sqYfq7k7VEzsdC9GTQ41JmUPlPFl+5rA=,iv:rIaNUjqUSmd5DCakq7O1oSBQF8y25/OKK+cXvGv6nKU=,tag:AnUPkFMSxuw98WPKfIOSlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hq2vn8nalmp9plfn4x6x9haxm3dv0jzv2mdx2f8p4ud2xwcdq0sfst6p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWUlJR2FJSk9ScWxIQTdO
            blhHdCs5b3pUS080T3RaaXhYZk1pTlcyUldVClh3ZzF0dTFGYld6NndLdEV3ZjBq
            V21vYmtmdzJPTkFyWlVrZkdOZzhNeFEKLS0tIG96Y21HaStEdjN3SHI0TllVT1N5
            MlhCdTR2bDNwbkFZRURzb2JRZ0tjMDQK0dwZKjoGgqdz30+ACagLD1xRX6Nx1Rm+
            qud65AxzGYPQ8qxjaH5uY66zj+kPLOEmfoTUbsOctMX5mEcumnh4bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-21T01:00:27Z"
    mac: ENC[AES256_GCM,data:FJq5FvcnmYQ6VXvMrc2xDelBOgWfAzjj99B9MLsqhscCugaBSN/MIexmQV9kdWYbv//AJDfj4mjezyIqQ55MiZ1sbC0mRgLXc3jly6Am8b0dRFJwTJacdbSxzWsWgmYe/MeplTytbAzEe/Y+U1YmaCpnbqaS16+cp73hf67cB6Q=,iv:Byrh5TrM5dFMmrtnHcUP3V6d8OcOhtgaudtQq4CNBOg=,tag:OtlJXIRKo7WCeqJM9xlE6A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
