backblaze:
    keyID: ENC[AES256_GCM,data:w7vtnO6dqUkO299Eqi+Nzy6sgRarvyCmSg==,iv:xxz8hF0aAn143Qg1W3JPLHo3CDVy/xLjYgpWaAVpmT4=,tag:nGTbEysBJ4DuXJo6/kvhrQ==,type:str]
    applicationKey: ENC[AES256_GCM,data:7cqmNg5HhFiachTyFTGPtociTPf3/UhctyfWa7mayw==,iv:7MfbGi57gfKv8QjirN9Qd0tDSrIjOFD3qG1M/Qj2t/E=,tag:ZGEbLGIm8R6668Xxx9DMyw==,type:str]
hcloud:
    token: ENC[AES256_GCM,data:5RS89h+BzIvFW/uKYhPhTU/HPSeN2P9FTWOdA1cWdPN7NUJL+RSosum5Sf7ooq71z+c68QoSWQIXNow++rPvaw==,iv:8Cd2a97yqIX9nz8IFvhH5WRTXDrL8oToUW8EwVYd1m0=,tag:RROXRHfDbKkXOCnrvLXwOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hq2vn8nalmp9plfn4x6x9haxm3dv0jzv2mdx2f8p4ud2xwcdq0sfst6p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWUlJR2FJSk9ScWxIQTdO
            blhHdCs5b3pUS080T3RaaXhYZk1pTlcyUldVClh3ZzF0dTFGYld6NndLdEV3ZjBq
            V21vYmtmdzJPTkFyWlVrZkdOZzhNeFEKLS0tIG96Y21HaStEdjN3SHI0TllVT1N5
            MlhCdTR2bDNwbkFZRURzb2JRZ0tjMDQK0dwZKjoGgqdz30+ACagLD1xRX6Nx1Rm+
            qud65AxzGYPQ8qxjaH5uY66zj+kPLOEmfoTUbsOctMX5mEcumnh4bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-20T04:11:45Z"
    mac: ENC[AES256_GCM,data:/0l0WQjKnuMZa1ox3SFVnA67uOCP5MdBRp8t1LLr1U1crMHFcCBJg96/6Xy7LH5/yduxzYtfGL16uMUV3F79DCMttzUFWeEazgvnmY64ueSyACwFimitZKsYgBkUNFCQrnHHG9qkHas04tBzJMNtWEjfYJfuZTWglR82cAnoHKQ=,iv:Va/aPBG3UZG/sQGULHldpam3cex53tV9ih9dLWnDa9o=,tag:pO6cX1p1kc780V14GrqejQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
