apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: cilium
  namespace: kube-system
spec:
  valuesContent: |-
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.42.0.0/16
        clusterPoolIpv6PodCIDRList:
          - fd42::/48
    devices: eth1

    prometheus:
      enabled: true

    operator:
      prometheus:
        enabled: true
      replicas: 1

    gatewayAPI:
      enable: true
    kubeProxyReplacement: strict

    hubble:
      metrics:
        enableOpenMetrics: false
      relay:
        enabled: false
      ui:
        enabled: false
