apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    extensionProviders:
      - name: "oauth2-proxy"
        envoyExtAuthzHttp:
          service: "oauth2-proxy.oauth2-proxy.svc.cluster.local"
          port: "4180"
          includeRequestHeadersInCheck: ["authorization", "cookie"]
          headersToUpstreamOnAllow:
            [
              "authorization",
              "path",
              "x-auth-request-user",
              "x-auth-request-email",
              "x-auth-request-access-token",
            ]
          headersToDownstreamOnDeny: ["content-type", "set-cookie"]
