apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    extensionProviders:
      - name: oauth2-proxy
        envoyExtAuthzHttp:
          service: oauth2-proxy.oauth2-proxy.svc.cluster.local
          port: "80"
          includeRequestHeadersInCheck:
            - authorization
            - cookie
          includeHeadersInCheck:
            - accept
            - authorization
            - cookie
            - from
            - proxy-authorization
            - user-agent
            - x-auth-request-redirect
            - x-forwarded-access-token
            - x-forwarded-email
            - x-forwarded-for
            - x-forwarded-host
            - x-forwarded-proto
            - x-forwarded-uri
            - x-forwarded-user
          includeAdditionalHeadersInCheck:
            X-Auth-Request-Redirect: https://%REQ(Host)%/%REQ(:PATH)%
          headersToUpstreamOnAllow:
            - authorization
            - cookie
            - path
            - x-auth-request-access-token
            - x-auth-request-email
            - x-auth-request-user
          headersToDownstreamOnDeny:
            - content-type
            - set-cookie
