apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        k8s:
          resources:
            limits:
              cpu: null
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1
    enablePrometheusMerge: false
    extensionProviders:
      - name: oauth2-proxy
        envoyExtAuthzHttp:
          service: oauth2-proxy.oauth2-proxy.svc.cluster.local
          port: "80"
          includeRequestHeadersInCheck:
            - Authorization
            - Cookie
            - X-Auth-Request-Redirect
          includeAdditionalHeadersInCheck:
            X-Auth-Request-Redirect: https://%REQ(Host)%/%REQ(:PATH)%
          headersToUpstreamOnAllow:
            - Authorization
            - Path
            - X-Auth-Request-Email
            - X-Auth-Request-Preferred-Username
            - X-Auth-Request-User
            - X-Forwarded-For
          headersToDownstreamOnDeny:
            - Content-Type
            - Set-Cookie
