apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ext-authz
spec:
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              - "*.stehessel.org"
            notHosts:
              - auth.stehessel.org
  selector:
    matchLabels:
      istio: ingressgateway
