apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redis
spec:
  interval: 5m
  type: oci
  url: oci://docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  labels:
    app.kubernetes.io/part-of: paperless-ngx
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: redis
  interval: 5m
  # Default values
  # https://artifacthub.io/packages/helm/bitnami/redis
  values:
    architecture: standalone
    auth:
      enabled: false
    global:
      storageClass: longhorn
    commonLabels:
      app.kubernetes.io/part-of: paperless-ngx
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gotenberg
spec:
  interval: 5m
  url: https://maikumori.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gotenberg
  labels:
    app.kubernetes.io/part-of: paperless-ngx
spec:
  releaseName: gotenberg
  chart:
    spec:
      chart: gotenberg
      sourceRef:
        kind: HelmRepository
        name: gotenberg
  interval: 5m
  # Default values
  # https://artifacthub.io/packages/helm/maikumori/gotenberg#values
  values:
    chromium:
      allowList: "file:///tmp/.*"
      disableJavaScript: true
    podLabels:
      app.kubernetes.io/part-of: paperless-ngx
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tika
spec:
  interval: 5m
  url: https://apache.jfrog.io/artifactory/tika
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tika
  labels:
    app.kubernetes.io/part-of: paperless-ngx
spec:
  releaseName: tika
  chart:
    spec:
      chart: tika
      sourceRef:
        kind: HelmRepository
        name: tika
  interval: 5m
  # Default values
  # https://github.com/apache/tika-helm/blob/main/values.yaml
  values:
    image:
      repository: ghcr.io/paperless-ngx/tika
      tag: latest
