apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx
resources:
  - deployment.yaml
  - helm.yaml
  - namespace.yaml
  - routes.yaml
  - secret.yaml
  - service.yaml
  - storage.yaml
