apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/name: paperless-ngx
  name: paperless-ngx
spec:
  parentRefs:
    - name: gateway
      namespace: ingress
      sectionName: https
  hostnames:
    - docs.stehessel.org
  rules:
    - backendRefs:
        - name: paperless-ngx
          namespace: paperless-ngx
          port: 80
