apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx
  labels:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/name: paperless-ngx
spec:
  selector:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/name: paperless-ngx
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
