apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data
  labels:
    app.kubernetes.io/name: paperless-ngx
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-media
  labels:
    app.kubernetes.io/name: paperless-ngx
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
