apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  labels:
    app.kubernetes.io/name: mealie
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mealie
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: data
      labels:
        app.kubernetes.io/name: mealie
    spec:
      containers:
        - name: mealie-app
          image: hkotel/mealie:api-v1.0.0beta-4
          env:
            - name: ALLOW_SIGNUP
              value: "true"
            - name: BASE_URL
              value: https://mealie.stehessel.org
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - containerPort: 9000
              name: app
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /app/data
              name: data
        - name: mealie-frontend
          image: hkotel/mealie:frontend-v1.0.0beta-4
          env:
            - name: API_URL
              value: http://mealie.mealie.svc.cluster.local:9000
          ports:
            - containerPort: 3000
              name: ui
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /app/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mealie
