apiVersion: v1
kind: Service
metadata:
  name: mealie
  labels:
    app.kubernetes.io/name: mealie
spec:
  selector:
    app.kubernetes.io/name: mealie
  ports:
    - name: app
      protocol: TCP
      port: 9000
      targetPort: app
    - name: ui
      protocol: TCP
      port: 80
      targetPort: ui
