apiVersion: v1
kind: Service
metadata:
  name: mealie
  labels:
    app.kubernetes.io/name: mealie
spec:
  selector:
    app.kubernetes.io/name: mealie
  ports:
    - name: app
      protocol: TCP
      port: 9000
      targetPort: app
    - name: ui
      protocol: TCP
      port: 80
      targetPort: ui
# ---
# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   labels:
#     app.kubernetes.io/name: mealie
#   name: mealie
# spec:
#   gateways:
#     - istio-system/gateway
#   hosts:
#     - mealie.stehessel.org
#   http:
#     - route:
#         - destination:
#             host: mealie.mealie.svc.cluster.local
#             port:
#               number: 9000
