apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie
  labels:
    app.kubernetes.io/name: mealie
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
