apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vector
spec:
  interval: 5m
  url: https://helm.vector.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  labels:
    app.kubernetes.io/name: vector
spec:
  releaseName: vector
  chart:
    spec:
      chart: vector
      sourceRef:
        kind: HelmRepository
        name: vector
  interval: 5m
  # Default values
  # https://github.com/vectordotdev/helm-charts/tree/develop/charts/vector
  values:
    role: Agent
    persistence:
      enabled: true
      hostPath:
        enabled: false
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: true
        address: 127.0.0.1:8686
        playground: false
      sources:
        kubernetes_logs:
          type: kubernetes_logs
        host_metrics:
          filesystem:
            devices:
              excludes: [binfmt_misc]
            filesystems:
              excludes: [binfmt_misc]
            mountPoints:
              excludes: ["*/proc/sys/fs/binfmt_misc"]
          type: host_metrics
        internal_metrics:
          type: internal_metrics
      sinks:
        prom_exporter:
          type: prometheus_exporter
          inputs: [host_metrics, internal_metrics]
          address: 0.0.0.0:9090
        loki:
          type: "loki"
          inputs: ["kubernetes_logs"]
          endpoint: http://loki-gateway.loki.svc.cluster.local
          encoding:
            codec: json
          labels:
            "pod_labels_*": |-
              {{ print "{{ kubernetes.pod_labels }}" }}
            "*": |-
              {{ print "{{ metadata }}" }}

        stdout:
          type: console
          inputs: [kubernetes_logs]
          encoding:
            codec: json
