apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vector-data-dir
  labels:
    app.kubernetes.io/name: vector
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
