apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  releaseName: authelia
  chart:
    spec:
      chart: authelia
      version: ">=0.8.57"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/authelia/chartrepo/tree/master/charts/authelia
  values:
    domain: stehessel.org
