apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: authelia
spec:
  parentRefs:
    - name: gateway
      namespace: ingress
      sectionName: https
  hostnames:
    - auth.stehessel.org
  rules:
    - backendRefs:
        - name: authelia
          namespace: authelia
          port: 80
