apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.3.2/deploy/kubernetes/hcloud-csi.yml
patchesStrategicMerge:
  - patch.yaml
