version: "3"

tasks:
  init:
    cmds:
      - terraform init
        -backend-config="access_key=$(sops --decrypt --extract '["backblaze"]["keyID"]' secrets/base.yaml)"
        -backend-config="secret_key=$(sops --decrypt --extract '["backblaze"]["applicationKey"]' secrets/base.yaml)"
      # - terraform init
    desc: Init terraform with backblaze backend

  apply:
    cmds:
      - terraform apply -auto-approve
      - terraform output --raw kubeconfig > kubeconfig.yaml
    desc: Apply terraform configuration

  clear:
    cmds:
      - terraform state rm $(terraform state list)
    desc: Clear terraform state

  destroy:
    cmds:
      - terraform destroy -auto-approve
      - rm -f kubeconfig.yaml
    desc: Destroy terraform resources
