version: "3"

tasks:
  init:
    cmds:
      - terraform init -upgrade
    desc: Init terraform

  apply:
    cmds:
      - terraform apply -auto-approve
      - terraform output --raw kubeconfig > kubeconfig.yaml
      - chmod 700 kubeconfig.yaml
    desc: Apply terraform configuration

  clear:
    cmds:
      - terraform state rm $(terraform state list)
    desc: Clear terraform state

  destroy:
    cmds:
      - terraform destroy -auto-approve
      - rm -f kubeconfig.yaml
    desc: Destroy terraform resources
