apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: podinfo
  namespace: podinfo

spec:
  parentRefs:
    - name: traefik-gateway

  hostnames:
    - stehessel.org

  rules:
    - matches:
        - path:
            type: Exact
            value: /

      backendRefs:
        - name: podinfo
          port: 80
          weight: 1
