apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: podinfo
spec:
  parentRefs:
    - name: gateway
      namespace: istio-ingress
      kind: Gateway
  hostnames:
    - stehessel.org
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      backendRefs:
        - name: podinfo
          namespace: podinfo
          port: 9898
          weight: 1
