apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc
  labels:
    app.kubernetes.io/name: podinfo
spec:
  oidc:
    provider:
      issuer: https://stehessel.eu.auth0.com
    clientID: ogY2U57PpLPzIEMDq0Tnd5BfBKOEQeDx
    clientSecret:
      name: oidc-auth0
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: podinfo
    namespace: podinfo
