apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
spec:
  interval: 5m
  type: oci
  url: oci://ghcr.io/kyverno/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  labels:
    app.kubernetes.io/name: kyverno
spec:
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
  interval: 5m
  # Default values
  # https://artifacthub.io/packages/helm/kyverno/kyverno
  values:
    cleanupJobs:
      admissionReports:
        image:
          tag: latest
        podLabels:
          app.kubernetes.io/component: admissionReports
          app.kubernetes.io/name: kyverno
          app.kubernetes.io/part-of: kyverno-cleanup
      clusterAdmissionReports:
        image:
          tag: latest
        podLabels:
          app.kubernetes.io/component: clusterAdmissionReports
          app.kubernetes.io/name: kyverno
          app.kubernetes.io/part-of: kyverno-cleanup
    customLabels:
      app.kubernetes.io/name: kyverno
    grafana:
      enabled: true
    image:
      pullPolicy: Always
    policyReportsCleanup:
      image:
        tag: latest
    webhooksCleanup:
      image:
        tag: latest
