apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
spec:
  interval: 5m
  url: https://kyverno.github.io/kyverno
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policies
  labels:
    app.kubernetes.io/name: kyverno-policies
spec:
  releaseName: kyverno-policies
  chart:
    spec:
      chart: kyverno-policies
      sourceRef:
        kind: HelmRepository
        name: kyverno
  interval: 5m
  # Default values
  # https://github.com/kyverno/kyverno/blob/main/charts/kyverno-policies/values.yaml
  values:
