apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
spec:
  parentRefs:
    - name: gateway
      namespace: ingress
      sectionName: http
  hostnames:
    - stehessel.org
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
            port: 443
      matches:
        - path:
            type: Exact
            value: /syncthing
      backendRefs:
        - name: syncthing
          namespace: syncthing
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: syncthing
spec:
  parentRefs:
    - name: gateway
      namespace: ingress
      sectionName: https
  hostnames:
    - stehessel.org
  rules:
    - matches:
        - path:
            type: Exact
            value: /syncthing
      backendRefs:
        - name: syncthing
          namespace: syncthing
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: TCPRoute
metadata:
  name: syncthing
spec:
  parentRefs:
    - name: gateway
      namespace: ingress
      sectionName: https
  hostnames:
    - stehessel.org
  rules:
    - backendRefs:
        - name: syncthing
          namespace: syncthing
          port: 22000
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: UDPRoute
metadata:
  name: syncthing
spec:
  parentRefs:
    - name: gateway
      namespace: ingress
      sectionName: https
  hostnames:
    - stehessel.org
  rules:
    - backendRefs:
        - name: syncthing
          namespace: syncthing
          port: 22000
