apiVersion: v1
kind: Service
metadata:
  name: syncthing
  labels:
    app.kubernetes.io/name: syncthing
spec:
  selector:
    app.kubernetes.io/name: syncthing
  ports:
    - name: ui
      protocol: TCP
      port: 8384
      targetPort: ui

    - name: sync-tcp
      protocol: TCP
      port: 22000
      targetPort: sync

    - name: sync-udp
      protocol: UDP
      port: 22000
      targetPort: sync
