apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-pvc
  labels:
    app.kubernetes.io/name: syncthing
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
