apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing
  labels:
    app.kubernetes.io/name: syncthing
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
