ignore: |
  *.sops.*
  flux-system/
  flux/istio/Base/
  terraform/hetzner/extra-manifests/gateway.yaml
extends: default
rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  comments:
    min-spaces-from-content: 1
  document-start: disable
  indentation: enable
  line-length: disable
  truthy:
    allowed-values: ["true", "false", "on"]
