apiVersion: v1
kind: Secret
metadata:
    name: oidc-auth0
stringData:
    client-secret: ENC[AES256_GCM,data:5Abf+pDCkg6mUtII9dmWI9xjG3rOXFJES0X52PqD6wz4Q328NiacwlLCS7pW3Xo+bt8nRwIon95Ce/OmDAuCWA==,iv:FmwD/cwhtWvf1TtqMKZvc87ONVwIE2Q4E1FlOC7Ketc=,tag:JJWoYMcIPE9IGgGVjsOxFQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hq2vn8nalmp9plfn4x6x9haxm3dv0jzv2mdx2f8p4ud2xwcdq0sfst6p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeHJlb2thUGtxYTdyNkU2
            K2NWTWlvcjh5WXYrMExvL3djQzZBbHJDYTFrCldsRXpSSEoxalkxQ0dCMVFXSk5N
            WTVqRHd2T0dsNmF5WTNYLzliUHFubDgKLS0tIDVSZkJoY2c3aHVGZmgzYVpGV0VG
            WkdjNlplOHJUWnRDbHpLVlJnMkxxd3MKHRBuIbB8rK9P9i+cnjjRk1g0btRlNbI+
            G4D2D5JjqS9KcFTa0CkiTZac68teFKRshs55BWRKrEZkMmcBJvg9Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T01:20:16Z"
    mac: ENC[AES256_GCM,data:ZRkAb8PV9pTXWD3Kkmd4i+2DPBcAQrmeD33uYzYFCZATF0hEElU9evU2u5oIbz4nxjqRU0t5+XsFiVCk/Gbs9Hohu5SUUhteXZpHyp/FzXfXkXvhxxYWnXuMY1WSoVBOR8DwzEVz2ZwKB5PJQwZ1zZzxnf/Ee5M0nD47yICRYvg=,iv:wS5jj/i721xJKZ8xMmikDwZsQX7MoHUjLcgbM14ilok=,tag:Gz3pLKwa2PoABvH3roPE0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
