apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
  dependsOn:
    - name: crds
    - name: infrastructure
    - name: istio
  interval: 2m0s
  path: ./flux/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s
  timeout: 5m0s
  wait: true
