apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
  dependsOn:
    - name: crds
  interval: 2m0s
  path: ./flux/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s
