# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: istio
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: cert-manager
#     - name: crds
#   interval: 2m0s
#   path: ./flux/istio
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: k3s
