apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: policy-reporter
spec:
  interval: 5m
  url: https://kyverno.github.io/policy-reporter
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-reporter
  labels:
    app.kubernetes.io/name: policy-reporter
spec:
  releaseName: policy-reporter
  chart:
    spec:
      chart: policy-reporter
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
  interval: 5m
  # Default values
  # https://artifacthub.io/packages/helm/policy-reporter/policy-reporter
  values:
    kyvernoPlugin:
      enabled: true
    metrics:
      enabled: true
    monitoring:
      grafana:
        namespace: monitoring-system
        dashboards:
          enabled: true
          label: grafana_dashboard
        folder:
          annotation: grafana_folder
          name: Policy Reporter
    ui:
      displayMode: dark
      enabled: true
      plugins:
        kyverno: true
