apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/name: policy-reporter
  name: podinfo
spec:
  parentRefs:
    - name: gateway
      namespace: ingress
      sectionName: https
  hostnames:
    - kyverno.stehessel.org
  rules:
    - backendRefs:
        - name: policy-reporter-ui
          namespace: policy-reporter
          port: 8080
