apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/name: policy-reporter
  name: policy-reporter
spec:
  gateways:
    - istio-system/gateway
  hosts:
    - kyverno.stehessel.org
  http:
    - route:
        - destination:
            host: policy-reporter-ui.policy-reporter.svc.cluster.local
            port:
              number: 8080
