apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
spec:
  interval: 30m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 5m
  # Default values
  # https://artifacthub.io/packages/helm/cert-manager/cert-manager
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller-arm
    installCRDs: true
    featureGates: ExperimentalGatewayAPISupport=true
