apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: porkbun-webhook
  namespace: porkbun-webhook
spec:
  releaseName: porkbun-webhook
  chart:
    spec:
      chart: porkbun-webhook
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: porkbun-webhook
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/mdonoughe/porkbun-webhook/blob/main/deploy/porkbun-webhook/values.yaml
  values:
    groupName: acme.stehessel.org
