apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
    labels:
        app.kubernetes.io/name: cert-manager
stringData:
    api_token: ENC[AES256_GCM,data:Ro6/13aqlEbCuVDNaIP7qK0y2GbXGlgb6gOoCgOdWrSoA8ZeVY8IKA==,iv:o2o8R46Nul0h9Fuk1f8eedXBzOypdZR7sQBZqZuis7w=,tag:oizLG04ZyW9yOZ1CqyjspQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hq2vn8nalmp9plfn4x6x9haxm3dv0jzv2mdx2f8p4ud2xwcdq0sfst6p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOGlkVExvM1BVVFlVa0ZJ
            QmphVk55WG5xL21veExiMmE1R2orNHRSK1FFCnR0YW8zTGhzOEZPeTZSL0lqYUdz
            UU1BbTlmaXNRVHc1NXp1Z0JmS1I5ZHMKLS0tIFlneWYxRjl5UGlQcnZPeGpCWGZY
            VGU2aUN1SjFZTFFNY2Qrb1RSNmdCcXMKhgD+AEcf4zSNN7zCITEEEviR4KoyS4NM
            dVc+rWsyWEC/pjWakSsG1NLdlXDAqcX7U4fIiDnC0dbClOItKQDrZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-14T21:01:14Z"
    mac: ENC[AES256_GCM,data:wZlj6gIjyQYsI7N9cZrKJQ62JIvBhy6IV/pq1SzrSexliuIe76ogk3axlZGDTlDnWUbTwXOewvmKSDusseWj9Dah7uDfhIq77zwp90MDAAIN35rpIn6xSyBv0FL6Wn3r7OHMO2+TZ4eKutZqaHsgG910enC6/9pjnVfZPUQjOyc=,iv:lcMGnq3VjquxjpoVrZbspB3W6vpzc893/bC2TtNFOSM=,tag:4L7gL7cYjNMo/iYIbKGf3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
