apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: trivy-operator
  labels:
    app.kubernetes.io/name: trivy-operator
spec:
  endpoints:
    - port: metrics
      metricRelabelConfigs:
        - sourceLabels: [exported_namespace]
          targetLabel: namespace
  namespaceSelector:
    matchNames:
      - trivy-operator
  selector:
    matchLabels:
      app.kubernetes.io/instance: trivy-operator
