apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  labels:
    app.kubernetes.io/name: oauth2-proxy
spec:
  releaseName: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: ">=6.12.0"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
  interval: 5m
  # Default values
  # https://github.com/oauth2-proxy/manifests/tree/main/helm/oauth2-proxy
  values:
    config:
      existingConfig: oauth2-proxy-config
      existingSecret: oauth2-proxy-github
