apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/name: whoami
  name: whoami
spec:
  parentRefs:
    - name: gateway
      namespace: ingress
      sectionName: https
  hostnames:
    - whoami.stehessel.org
  rules:
    - backendRefs:
        - name: whoami
          namespace: whoami
          port: 80
