apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/name: whoami
  name: whoami
spec:
  parentRefs:
    - name: gateway
      namespace: ingress
      sectionName: https
  hostnames:
    - whoami.stehessel.org
  rules:
    - backendRefs:
        - name: whoami
          namespace: whoami
          port: 80
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: X-Auth-Request-User
                value: stehessel
              - name: X-Auth-Request-Email
                value: login@stephan.sh
