apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    app.kubernetes.io/name: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: ">=6.19.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://artifacthub.io/packages/helm/bitnami/external-dns
  values:
    cloudflare:
      email: accounts@stehessel.de
      proxied: false
      secretName: cloudflare-dns
    extraArgs:
      exclude-target-net: 10.0.0.0/8
    provider: cloudflare
    sources:
      - gateway-httproute
      - ingress
      - istio-gateway
      - istio-virtualservice
      - service
    logLevel: debug
