apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns
    namespace: external-dns
    labels:
        app.kubernetes.io/name: external-dns
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:1y2bg1pQ5PSxAXcE7U0v8Vy9/YFA09K8LJ4DjOT+yct2Xn0PzWktdA==,iv:YEr+RYu4nIhnEzNE25EzF6Ql7jvOXYmguJYT46AllfA=,tag:EL9dUTDEchzqW975zxYRLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hq2vn8nalmp9plfn4x6x9haxm3dv0jzv2mdx2f8p4ud2xwcdq0sfst6p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYmdiYzl2cTJJM3ZONjha
            cmNZREkvKzBvNUxqVlZ0eXJnT1JkSzJLTlhJCjJNNnBkQ0l5WDE4TzUzYjhYR0Vm
            NGY3cHZUMGdoSnNUTnFJTC9mWEtDMTgKLS0tIDRpR0pRNzVDaVIvSlJ5d3RWcXBm
            THNsWDE2ZExaMmx1SlVjVmhxZkF4N3cKuPKIw2VRKLIMsMlOdLU1ek4zO5t3XdZ1
            KRfqtFiOKZG5LT0AB+wROwZ9Iv8pILIKc8UoCTUCSnXwLYmj6KIvuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T16:19:35Z"
    mac: ENC[AES256_GCM,data:qxVmav0T2FwYjH1wAAs8FJWpkzf9KNpxRJ20aVZlb+PSoaWtBlWkcozX9+07Ebs62OxSCefIlc22VWSb85A2p0Fl/EITa56g5Iexwn9aNiwaA193RPvsPZzfrIRo8ulwoy7sSvndKGZ0Rk0FdF7RDlGj3wQCiwEbRmEDlubGuDM=,iv:hAtsPrSQg61kOpDbitZvzEZfxuH3Zr9EPM/pcIpDYzs=,tag:ms0sdMm8VPAW5gdZPAAYxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
